//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarullinExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act
    {
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int IdUser { get; set; }
        public int IdPhone { get; set; }
        public int IdTypeFault { get; set; }
        public Nullable<int> IdComsumables { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Comsumables Comsumables { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual TypeFault TypeFault { get; set; }
        public virtual User User { get; set; }
    }
}
