//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarullinExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdOperation { get; set; }
        public int IdPhone { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DataDeal { get; set; }
        public Nullable<int> IdBid { get; set; }
    
        public virtual Bid Bid { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual User User { get; set; }
    }
}
