//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarullinExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePhone
    {
        public TypePhone()
        {
            this.Phone = new HashSet<Phone>();
        }
    
        public int Id { get; set; }
        public string NameType { get; set; }
    
        public virtual ICollection<Phone> Phone { get; set; }
    }
}
