//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YarullinExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeFault
    {
        public TypeFault()
        {
            this.Act = new HashSet<Act>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Act> Act { get; set; }
    }
}
